### ISSUE TITLE
Issue when sending images

### ISSUE THREAD

**Issue by AlexSFeather** [MaiRiosIPla/unshittify-discord#1]
When you drag and drop an image into the text field it moves far down beyond the application window like on the screenshot below making the theme problematic to use

![Image](https://github.com/user-attachments/assets/2d4e9efd-ae8f-44cb-829d-014a80921c13)

**Comment by Xaero252** [comment]
My solution for this has been this custom css, though I understand this also has some potentially undesired effects. Basically I allow the container with the textbox and the attachments to grow in size indefinitely, then I limit the textbox to 22em in height and it's parent to 23em in height to allow for padding. I then force the textbox to overflow with a scrollbar for longer messages, and style the scrollbar in an unobtrusive way.

Ends up working out okay, here's a screenshot with no attachments:

![Image](https://github.com/user-attachments/assets/e26750f2-57d2-4273-aac7-513f4989334e)

And here's a screenshot with attachments:

![Image](https://github.com/user-attachments/assets/c8c9554e-eef8-4e23-8199-c6d11f4ff1dc)

```
.scrollableContainer__74017 {
  max-height: unset !important;
  overflow-y: unset !important;
  overflow-x: unset !important;
}

.inner__74017 {
  max-height: 23em;
}

.textArea__74017 {
  max-height: 22em !important;
  overflow-y: auto;
}

::-webkit-scrollbar {
  width: 5px;
  height: 5px ;
}

::-webkit-scrollbar-thumb {
  background-color: #666770 !important;
  border-radius: 10px;
}

::-webkit-scrollbar-track {
  background-color: rgb(255 255 255 / 10%) !important;
  border-radius: 10px;
}
```

**Comment by MaiRiosIPla** [comment]
Idk why, but the issue closed automatically. Anyway, the fix, which should allow for scaling of the bar, regardless of the kind of media (be it files or text) was the following:

```css
/* Chat input bar (OLD) */
.channelTextArea_f75fb0   {
	margin-bottom: var(--space-xs);
	--custom-channel-textarea-text-area-max-height: 56px;
	--custom-channel-textarea-text-area-height: var(
		--custom-channel-textarea-text-area-max-height
	);
}
/* Chat input bar (FIXED) */
.channelTextArea_f75fb0   {
	margin-bottom: var(--space-xs);
	.inner__74017 {
		--custom-channel-textarea-text-area-max-height: 56px;
		--custom-channel-textarea-text-area-height: var(
			--custom-channel-textarea-text-area-max-height
		);
	}
}
```

![Image](https://github.com/user-attachments/assets/642695cd-5a99-43ba-89d3-36f9d581e22d)
