### ISSUE TITLE
Move Refreshed Seamless Chat Bar to it's own optional

### ISSUE THREAD

**Issue by PassiveLemon** [MaiRiosIPla/unshittify-discord#12]
Could the Refreshed Seamless Chat not be imported by default? I think an optional addition like the rounded icons would be nice, I had modified it specifically so it simply just moved the typing indicator above without any fancy UI additions but this default import undoes all that I had done lol:
```css
/* Move typing indicator above textbox */
.visual-refresh .form_f75fb0 {
  display: flex;
  flex-direction: column;
  padding: 0px 4px 4px 4px !important;
  /* Chat bar */
  .channelTextArea_f75fb0 {
    margin-bottom: 4px;
    margin-right: 4px;
  }
  /* Slowmode bar + Typing indicator */
  .base_b88801 {
    position: static;
    order: -1;
    .typing_b88801,
    .typingDots_b88801,
    .cooldownText_b21699 {
      &.typingDots_b88801 {
        transform: translateX(4px);
      }
      &.cooldownText_b21699 {
        transform: translateY(1px);
      }
    }
  }
}
```

I also noticed that with `--rscb-no-jump-chat: 0;` (not related to my snippet above) it sometimes leaves the empty space below
